### ISSUE TITLE
Zero dividing issue

### ISSUE THREAD

**Issue by LiLejia** [esilverberg/ios-image-filters#5]
There may be some zero dividing issues, for example:

void filterPosterize(UInt8 _pixelBuf, UInt32 offset, void *context)
{
    int levels = *((int_)context);
    int step = 255 / levels;

```
int r = offset;
int g = offset+1;
int b = offset+2;

int red = pixelBuf[r];
int green = pixelBuf[g];
int blue = pixelBuf[b];

pixelBuf[r] = SAFECOLOR((red / step) * step);
pixelBuf[g] = SAFECOLOR((green / step) * step);
pixelBuf[b] = SAFECOLOR((blue / step) * step);
```

}

I once crashed on int step = 255 / levels;

**Comment by esilverberg** [comment]
I just pushed a fix for this, thanks for the catch.
