### ISSUE TITLE
EXC_BAD_ACCESS problem

### ISSUE THREAD

**Issue by pandizajner** [esilverberg/ios-image-filters#8]
Hello,

I try to use ios-image-filters, but not everything is working for me.
Examplary if I call 'lomo' or 'adjust', Xcode says: EXC_BAD_ACCESS code=2 in line "pixelBuf[r] = SAFECOLOR(red \* (1 + val.r));" for adjusting.
I'm using ARC, so I loaded classes with flag -fno-objc-arc, but even if I tried .xcodeproj attached to the package - it does the same.

I'm not very experienced in Obj-C, so could you help me to fix this issue?

**Comment by nadangergeo** [comment]
+1

**Comment by iclems** [comment]
Same issue here, investigating...

**Comment by RyanBertrand** [comment]
CFDataGetBytePtr() returns a read-only pointer.  You need to grab a mutable version.  See below.  Works on iOS6
- (UIImage_) applyFilter:(FilterCallback)filter context:(void_)context
  {
  CGImageRef inImage = self.CGImage;
  CFDataRef m_DataRef = CGDataProviderCopyData(CGImageGetDataProvider(inImage));
  int length = CFDataGetLength(m_DataRef);
  CFMutableDataRef m_DataRefEdit = CFDataCreateMutableCopy(NULL,length,m_DataRef);
  UInt8 \* m_PixelBuf = (UInt8 *) CFDataGetMutableBytePtr(m_DataRefEdit);
  
  for (int i=0; i<length; i+=4)
  {
      filter(m_PixelBuf,i,context);
  }  
  
  CGContextRef ctx = CGBitmapContextCreate(m_PixelBuf,  
                                           CGImageGetWidth(inImage),  
                                           CGImageGetHeight(inImage),  
                                           CGImageGetBitsPerComponent(inImage),
                                           CGImageGetBytesPerRow(inImage),  
                                           CGImageGetColorSpace(inImage),  
                                           CGImageGetBitmapInfo(inImage) 
                                           ); 
  
  CGImageRef imageRef = CGBitmapContextCreateImage(ctx);  
  CGContextRelease(ctx);
  UIImage *finalImage = [UIImage imageWithCGImage:imageRef];
  CGImageRelease(imageRef);
  CFRelease(m_DataRef);
  return finalImage;

}

**Comment by danlipert** [comment]
Ryan you really saved me!  Thanks for the snippet! IOS 6.0 broke the hell out of my apps

**Comment by danielchong** [comment]
Ryan, thanks for saving me too. Just 1 comment - I think we need a line to release m_DataRefEdit:

```
CFRelease(m_DataRefEdit);
```

**Comment by esilverberg** [comment]
Submit a pull request and I am happy to merge into this project
